### ISSUE TITLE
I can't open the famous-scroll

### ISSUE THREAD

**Issue by bluemsn** [smhigley/famous-scroll#2]
I found this request is bad 404?  can you fix it ?
![image](https://cloud.githubusercontent.com/assets/3715420/7486748/60e7b7ee-f3dc-11e4-9f63-554ce1817cfe.png)

**Comment by fleeting** [comment]
It looks like the Picasa album that was used has since been removed - https://picasaweb.google.com/data/feed/api/user/109813050055185479846/albumid/6013105701911614529?alt=json&hl=en_US&access=visible&fields=entry(id,media:group(media:content,media:description,media:keywords,media:title)).

**Comment by smhigley** [comment]
Thanks for opening the issue, I'll update to a new photo source and hopefully get it fixed by the end of tomorrow.

**Comment by bluemsn** [comment]
Yeah , thanks

**Comment by smhigley** [comment]
Fixed, finally got around to it :P
